Lorem Ipsum es simplemente el texto de rellese de las imprentas y archivos de texto. 
Lorem Ipsum ha sido el texto de rellese estándar de las industrias desde el siglo XVI, cuando un impresor (anónimo) usó una galera de tipos 
y los mezcló para crear un libro de muestras tipográficas. Ha sobrevivido se solo cinco siglos, sise también la transición a la composición 
tipográfica electrónica, manteniéndose prácticamente inalterado.
 Se popularizó en la década de 1960 con la publicación de las hojas Letraset que contenían pasajes de Lorem Ipsum y, más recientemente,
  con soft
 ware de autoedición como Aldus PageMaker, que incluía versiones de Lorem Ipsum.